/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2023-03-03 03:58:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/view/footer.jsp", Long.valueOf(1677815604919L));
    _jspx_dependants.put("/view/header.jsp", Long.valueOf(1677815483657L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1677127217112L));
    _jspx_dependants.put("jar:file:/C:/Users/NGUYEN%20DUC%20VIET/eclipse-workspace3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FashionWeb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"index.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write(" rel=\"\r\n");
      out.write("	stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"index.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write(" rel=\"\r\n");
      out.write("	stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("	<nav class=\"navbar fixed-top navbar-expand-lg navbar-light bg-white\">\r\n");
      out.write("		<!-- Container wrapper -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Toggle button -->\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-mdb-toggle=\"collapse\"\r\n");
      out.write("				data-mdb-target=\"#navbarSupportedContent1\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent1\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<i class=\"fas fa-bars\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<!-- Collapsible wrapper -->\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent1\">\r\n");
      out.write("				<!-- Navbar brand -->\r\n");
      out.write("				<a class=\"navbar-brand mt-2 mt-sm-0\" href=\"https://mdbootstrap.com/\">\r\n");
      out.write("					<img\r\n");
      out.write("					src=\"https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp\"\r\n");
      out.write("					height=\"20\" alt=\"MDB Logo\" loading=\"lazy\" />\r\n");
      out.write("				</a>\r\n");
      out.write("				<!-- Left links -->\r\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item active\"><a class=\"nav-link \"\r\n");
      out.write("						href=\"https://mdbootstrap.com/\">Home</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"https://mdbootstrap.com/docs/standard/\">About MDB</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"https://mdbootstrap.com/docs/standard/getting-started/installation/\">Free\r\n");
      out.write("							download</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"https://mdbootstrap.com/education/bootstrap/\">Free\r\n");
      out.write("							tutorials</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<!-- Left links -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Collapsible wrapper -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Right elements -->\r\n");
      out.write("			<div class=\"d-flex align-items-center\">\r\n");
      out.write("				<!-- Icon -->\r\n");
      out.write("				<a class=\"nav-link me-3\" href=\"#\"> <i\r\n");
      out.write("					class=\"fas fa-shopping-cart\"></i> <span\r\n");
      out.write("					class=\"badge rounded-pill badge-notification bg-danger\">1</span>\r\n");
      out.write("				</a> <a class=\"nav-link me-3\" href=\"#\"> <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("				</a> <a class=\"nav-link me-3\" href=\"#\"> <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("				</a> <a href=\"https://github.com/mdbootstrap/bootstrap-material-design\"\r\n");
      out.write("					class=\"border rounded px-2 nav-link\" target=\"_blank\"> <i\r\n");
      out.write("					class=\"fab fa-github me-2\"></i>MDB GitHub\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Right elements -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Container wrapper -->\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Navbar -->");
      out.write("\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("	<!-- carousel -->\r\n");
      out.write("	<div id=\"carouselExampleCaptions\" class=\"carousel slide carousel-fade\"\r\n");
      out.write("		data-mdb-ride=\"carousel\">\r\n");
      out.write("		<div class=\"carousel-indicators\">\r\n");
      out.write("			<button type=\"button\" data-mdb-target=\"#carouselExampleCaptions\"\r\n");
      out.write("				data-mdb-slide-to=\"0\" class=\"active\" aria-current=\"true\"\r\n");
      out.write("				aria-label=\"Slide 1\"></button>\r\n");
      out.write("			<button type=\"button\" data-mdb-target=\"#carouselExampleCaptions\"\r\n");
      out.write("				data-mdb-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("			<button type=\"button\" data-mdb-target=\"#carouselExampleCaptions\"\r\n");
      out.write("				data-mdb-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"carousel-inner\">\r\n");
      out.write("			<div class=\"carousel-item active\">\r\n");
      out.write("				<img\r\n");
      out.write("					src=\"https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg\"\r\n");
      out.write("					class=\"d-block w-100\" alt=\"Wild Landscape\" />\r\n");
      out.write("				<div class=\"mask\" style=\"background-color: rgba(0, 0, 0, 0.4)\"></div>\r\n");
      out.write("				<div class=\"carousel-caption d-none d-sm-block mb-5\">\r\n");
      out.write("					<h1 class=\"mb-4\">\r\n");
      out.write("						<strong>Learn Bootstrap 5 with MDB</strong>\r\n");
      out.write("					</h1>\r\n");
      out.write("\r\n");
      out.write("					<p>\r\n");
      out.write("						<strong>Best & free guide of responsive web design</strong>\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("					<p class=\"mb-4 d-none d-md-block\">\r\n");
      out.write("						<strong>The most comprehensive tutorial for the Bootstrap\r\n");
      out.write("							5. Loved by over 3 000 000 users. Video and written versions\r\n");
      out.write("							available. Create your own, stunning website.</strong>\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("					<a target=\"_blank\"\r\n");
      out.write("						href=\"https://mdbootstrap.com/education/bootstrap/\"\r\n");
      out.write("						class=\"btn btn-outline-white btn-lg\">Start free tutorial <i\r\n");
      out.write("						class=\"fas fa-graduation-cap ms-2\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<img\r\n");
      out.write("					src=\"https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg\"\r\n");
      out.write("					class=\"d-block w-100\" alt=\"Exotic Fruits\" />\r\n");
      out.write("				<div class=\"mask\" style=\"background-color: rgba(0, 0, 0, 0.4)\"></div>\r\n");
      out.write("				<div class=\"carousel-caption d-none d-md-block mb-5\">\r\n");
      out.write("					<h1 class=\"mb-4\">\r\n");
      out.write("						<strong>Learn Bootstrap 5 with MDB</strong>\r\n");
      out.write("					</h1>\r\n");
      out.write("\r\n");
      out.write("					<p>\r\n");
      out.write("						<strong>Best & free guide of responsive web design</strong>\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("					<p class=\"mb-4 d-none d-md-block\">\r\n");
      out.write("						<strong>The most comprehensive tutorial for the Bootstrap\r\n");
      out.write("							5. Loved by over 3 000 000 users. Video and written versions\r\n");
      out.write("							available. Create your own, stunning website.</strong>\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("					<a target=\"_blank\"\r\n");
      out.write("						href=\"https://mdbootstrap.com/education/bootstrap/\"\r\n");
      out.write("						class=\"btn btn-outline-white btn-lg\">Start free tutorial <i\r\n");
      out.write("						class=\"fas fa-graduation-cap ms-2\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("			data-mdb-target=\"#carouselExampleCaptions\" data-mdb-slide=\"prev\">\r\n");
      out.write("			<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("				class=\"visually-hidden\">Previous</span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("			data-mdb-target=\"#carouselExampleCaptions\" data-mdb-slide=\"next\">\r\n");
      out.write("			<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("				class=\"visually-hidden\">Next</span>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!--Main layout-->\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Navbar -->\r\n");
      out.write("			<nav class=\"navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2\"\r\n");
      out.write("				style=\"background-color: #607D8B\">\r\n");
      out.write("				<!-- Container wrapper -->\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Navbar brand -->\r\n");
      out.write("					<a class=\"navbar-brand\" href=\"#\">Categories:</a>\r\n");
      out.write("\r\n");
      out.write("					<!-- Toggle button -->\r\n");
      out.write("					<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("						data-mdb-toggle=\"collapse\"\r\n");
      out.write("						data-mdb-target=\"#navbarSupportedContent2\"\r\n");
      out.write("						aria-controls=\"navbarSupportedContent2\" aria-expanded=\"false\"\r\n");
      out.write("						aria-label=\"Toggle navigation\">\r\n");
      out.write("						<i class=\"fas fa-bars\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("\r\n");
      out.write("					<!-- Collapsible wrapper -->\r\n");
      out.write("					<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent2\">\r\n");
      out.write("						<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Link -->\r\n");
      out.write("							<li class=\"nav-item acitve\"><a class=\"nav-link text-white\"\r\n");
      out.write("								href=\"#\">All</a></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link text-white\" href=\"#\">Shirts</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link text-white\" href=\"#\">Sport\r\n");
      out.write("									wears</a></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link text-white\" href=\"#\">Outwears</a>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("						<!-- Search -->\r\n");
      out.write("						<form class=\"w-auto py-1\" style=\"max-width: 12rem\">\r\n");
      out.write("							<input type=\"search\" class=\"form-control rounded-0\"\r\n");
      out.write("								placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Container wrapper -->\r\n");
      out.write("			</nav>\r\n");
      out.write("			<!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Products -->\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"col-ms-9\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- End Products -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Pagination -->\r\n");
      out.write("			<nav aria-label=\"Page navigation example\"\r\n");
      out.write("				class=\"d-flex justify-content-center mt-3\">\r\n");
      out.write("				<ul class=\"pagination\">\r\n");
      out.write("					<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\"\r\n");
      out.write("						aria-label=\"Previous\"> <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"page-item active\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("					<li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("					<li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("					<li class=\"page-item\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("					<li class=\"page-item\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("					<li class=\"page-item\"><a class=\"page-link\" href=\"#\"\r\n");
      out.write("						aria-label=\"Next\"> <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("					</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<!-- Pagination -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("	<!--Main layout-->\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer class=\"text-center text-white mt-4\"\r\n");
      out.write("		style=\"background-color: #607D8B\">\r\n");
      out.write("\r\n");
      out.write("		<!--Call to action-->\r\n");
      out.write("		<div class=\"pt-4 pb-2\">\r\n");
      out.write("			<a class=\"btn btn-outline-white footer-cta mx-2\"\r\n");
      out.write("				href=\"https://mdbootstrap.com/docs/jquery/getting-started/download/\"\r\n");
      out.write("				target=\"_blank\" role=\"button\">Download MDB <i\r\n");
      out.write("				class=\"fas fa-download ms-2\"></i>\r\n");
      out.write("			</a> <a class=\"btn btn-outline-white footer-cta mx-2\"\r\n");
      out.write("				href=\"https://mdbootstrap.com/education/bootstrap/\" target=\"_blank\"\r\n");
      out.write("				role=\"button\">Start free tutorial <i\r\n");
      out.write("				class=\"fas fa-graduation-cap ms-2\"></i>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--/.Call to action-->\r\n");
      out.write("\r\n");
      out.write("		<hr class=\"text-dark\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Section: Social media -->\r\n");
      out.write("			<section class=\"mb-3\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Facebook -->\r\n");
      out.write("				<a class=\"btn-link btn-floating btn-lg text-white\" href=\"#!\"\r\n");
      out.write("					role=\"button\" data-mdb-ripple-color=\"dark\"><i\r\n");
      out.write("					class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("\r\n");
      out.write("				<!-- Twitter -->\r\n");
      out.write("				<a class=\"btn-link btn-floating btn-lg text-white\" href=\"#!\"\r\n");
      out.write("					role=\"button\" data-mdb-ripple-color=\"dark\"><i\r\n");
      out.write("					class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("\r\n");
      out.write("				<!-- Google -->\r\n");
      out.write("				<a class=\"btn-link btn-floating btn-lg text-white\" href=\"#!\"\r\n");
      out.write("					role=\"button\" data-mdb-ripple-color=\"dark\"><i\r\n");
      out.write("					class=\"fab fa-google\"></i></a>\r\n");
      out.write("\r\n");
      out.write("				<!-- Instagram -->\r\n");
      out.write("				<a class=\"btn-link btn-floating btn-lg text-white\" href=\"#!\"\r\n");
      out.write("					role=\"button\" data-mdb-ripple-color=\"dark\"><i\r\n");
      out.write("					class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("\r\n");
      out.write("				<!-- YouTube -->\r\n");
      out.write("				<a class=\"btn-link btn-floating btn-lg text-white\" href=\"#!\"\r\n");
      out.write("					role=\"button\" data-mdb-ripple-color=\"dark\"><i\r\n");
      out.write("					class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("				<!-- Github -->\r\n");
      out.write("				<a class=\"btn-link btn-floating btn-lg text-white\" href=\"#!\"\r\n");
      out.write("					role=\"button\" data-mdb-ripple-color=\"dark\"><i\r\n");
      out.write("					class=\"fab fa-github\"></i></a>\r\n");
      out.write("			</section>\r\n");
      out.write("			<!-- Section: Social media -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Grid container -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("		<div class=\"text-center p-3\"\r\n");
      out.write("			style=\"background-color: rgba(0, 0, 0, 0.2); text-color: #E0E0E0\">\r\n");
      out.write("			© 2022 Copyright: <a class=\"text-white\"\r\n");
      out.write("				href=\"https://mdbootstrap.com/\">MDBootstrap.com</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /view/home.jsp(25,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/view/index.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /view/header.jsp(25,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/view/index.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /view/home.jsp(167,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/view/home.jsp(167,6) '${listP}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listP}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /view/home.jsp(167,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<div class=\"col-lg-4 col-md-6 md-4\">\r\n");
            out.write("								<div class=\"card h-100\" style=\"width: 18rem;\">\r\n");
            out.write("									<img src=\"image/product/1.png\" class=\"card-img-top\"\r\n");
            out.write("										alt=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("									<div class=\"card-body\">\r\n");
            out.write("										<h5 class=\"card-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("										<p class=\"card-text\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("										<p class=\"card-text\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("										<p class=\"card-text\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("										<a href=\"#\" class=\"btn btn-primary\">Buy now</a>\r\n");
            out.write("									</div>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
